# Site
name: Caltech Undergraduate Admissions Blog
title: "Caltech Undergraduate Admissions Blog"
description: "Explore life at Caltech!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: "/blog" 
include: ["_pages"] 
permalink: /:title/

# Authors
authors:
  authors:
  andrew:
    name: Andrew
    display_name: I Think I Chan    
    avatar: 'assets/profilepics/andrew.jpg'
    description: "I'm a senior from Denver, Colorado (the land of Patagonia jackets and 
    unpredictable weather). At Caltech I'm on the fencing team foil squad captain and SAAC 
    representative, a member of chemistry club and ultimate frisbee team, and the Fleming House 
    food committee representative. In my free time, I like to hike, write poetry, shoot photos, 
    and explore LA for trendy food."
  brian:
    name: Brian
    display_name: Brian
    avatar: 'assets/profilepics/briannguyen.jpg'
    description: "I'm a junior from Brooklyn, New York."
  sunny: 
    name: Sunny
    display_name: Just a Sunny Day 
    avatar: 'assets/profilepics/sunny.jpg'
    description: "I'm from Vancouver, BC where it rains over 200 days a year. At Caltech, 
    I serve on the excomm of the Caltech Y and Society of Women Engineers and play piano 
    with the chamber music program. When I'm not doing sets and lab work, I enjoy hiking, 
    shopping, cooking, drawing, and scouring the internet for items to add to her never-ending 
    bucket list."
  tessa: 
    name: tessa
    display_name: Tesseract 
    avatar: 'assets/profilepics/tessa.jpg'
    description: "I grew up in the Seattle area and moved to Southern California to attend 
    Pitzer College in Claremont (and for the sunshine!) I graduated with a B.A. in Anthropology, 
    inspired by my love of museums and material culture and studied abroad in the Amazon region 
    of Brazil. After interning at The Getty Foundation, I worked in museum education at Huntington 
    Library (just down the street from Caltech). Even though I come from a humanities background, 
    I am a Techer at heart who always wants to hear about what students are working on in the lab 
    so I can live vicariously through them."
    
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-katex
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
